# fly.toml file generated for bet-explorer2 on 2023-01-18T00:03:47-03:00

app = "bet-explorer2"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  [build.args]
    NODE_VERSION = "14"
    PHP_VERSION = "8.1"

[env]
  APP_ENV = "production"
  APP_KEY = "base64:wR7tLLYFMMqVR6JvmiELrN8cHubk1+KY7VZXVK7gt3s="
  BOT_TOKEN = "830113645:AAGSt94gcNzKjiHoHrQLSDeDUTGsBzSaGNw"
  DATA_URL = "https://lv.scorebing.com/ajax/score/data"
  DB_CONNECTION = "mysql"
  DB_DATABASE = "bet_explorer"
  DB_HOST = "168.138.135.207"
  DB_PASSWORD = "pOzTnJ6Pe[)xg*oV"
  DB_PORT = "3306"
  DB_USERNAME = "bet_explorer"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  TELEGRAM_TOKEN = "830113645:AAGSt94gcNzKjiHoHrQLSDeDUTGsBzSaGNw"
  VITE_PUSHER_APP_CLUSTER = "${PUSHER_APP_CLUSTER}"
  VITE_PUSHER_APP_KEY = "${PUSHER_APP_KEY}"
  VITE_PUSHER_HOST = "${PUSHER_HOST}"
  VITE_PUSHER_PORT = "${PUSHER_PORT}"
  VITE_PUSHER_SCHEME = "${PUSHER_SCHEME}"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[processes]
  app = ""
  cron = "cron -f"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[servic
